import "./styles.css";

type Study = "study1" | "study2";
type Step = "setup" | "training" | "results";
const app = document.querySelector<HTMLElement>("#app");
if (!app) throw new Error("application root is missing");
const studies = {
  study1: { name: "Same-singer synthesis", description: "Reconstruct the PJS vocalist from score, phonemes, timing, pitch, and observed F0.", setup: "A same-singer diagnostic using the fixed PJS song-disjoint split." },
  study2: { name: "Content-and-melody transfer", description: "Preserve source vocal content, timing, and melody over a different instrumental.", setup: "A controlled source/target remix with explicit pair and alignment settings." },
} as const;
app.innerHTML = `<div class="shell"><header class="topbar"><div class="brand-mark">S</div><div><div class="brand">SingAlign</div><div class="subtitle">Research workspace</div></div><div class="dataset">PJS · reproducible studies</div></header><main id="content"></main></div>`;
const content = document.querySelector<HTMLElement>("#content")!;

function landing(): void {
  content.innerHTML = `<section class="landing-card"><div class="eyebrow">Research workflow</div><h1>Choose a study</h1><p class="lead">Run a focused, reproducible singing experiment.</p><div class="study-grid">${(["study1", "study2"] as Study[]).map((id) => `<label class="study-card"><input type="radio" name="study" value="${id}" ${id === "study1" ? "checked" : ""}><span class="study-number">${id === "study1" ? "01" : "02"}</span><span><strong>${studies[id].name}</strong><small>${studies[id].description}</small></span></label>`).join("")}</div><p id="landing-note" class="note"></p><button id="continue" class="primary">Continue <span>→</span></button></section>`;
  const note = document.querySelector<HTMLElement>("#landing-note")!;
  const selected = (): Study => document.querySelector<HTMLInputElement>('input[name="study"]:checked')!.value as Study;
  const update = (): void => { note.textContent = studies[selected()].setup; };
  document.querySelectorAll<HTMLInputElement>('input[name="study"]').forEach((input) => input.addEventListener("change", update));
  update();
  document.querySelector<HTMLButtonElement>("#continue")!.onclick = () => workflow(selected());
}

function workflow(study: Study): void {
  let step: Step = "setup"; let runId = ""; let evaluationRunId = ""; let comparisonRunId = "";
  const steps: Step[] = ["setup", "training", "results"];
  const draw = (): void => {
    content.innerHTML = `<div class="workflow-head"><div><div class="eyebrow">Study ${study === "study1" ? "01" : "02"}</div><h1>${studies[study].name}</h1><p>${studies[study].description}</p></div><button id="change" class="quiet">Change study</button></div><nav class="stepper">${steps.map((item, i) => `<button class="step ${item === step ? "active" : ""}" data-step="${item}"><span>${i + 1}</span>${item.charAt(0).toUpperCase() + item.slice(1)}</button>`).join("")}</nav><section id="stage" class="stage"></section>`;
    document.querySelector<HTMLButtonElement>("#change")!.onclick = landing;
    document.querySelectorAll<HTMLButtonElement>(".step").forEach((button) => { button.onclick = () => { step = button.dataset.step as Step; draw(); }; });
    const stage = document.querySelector<HTMLElement>("#stage")!;
    if (study === "study2" && step === "training") window.setTimeout(() => stage.insertAdjacentHTML("beforeend", `<p class="note">The target is pure instrumental accompaniment rendered from the MusicXML score. It is not another vocal recording and does not modify the source vocal; the source remains the content and melody reference.</p>`), 0);
    if (study === "study2" && step === "training") window.setTimeout(() => { const target = document.querySelector<HTMLInputElement>("#target"); if (!target) return; target.value = "reports/study-2/fixed-instrumental.wav"; const label = target.parentElement; if (label) label.firstChild!.textContent = "Rendered target instrumental"; const score = document.createElement("label"); score.innerHTML = "Target score (MusicXML)<input id=\"target-score\" value=\"data/raw/pjs/PJS_corpus_ver1.1/pjs052/pjs052.musicxml\">"; const render = document.createElement("button"); render.id = "render-target"; render.className = "quiet"; render.textContent = "Render target instrumental"; target.parentElement?.before(score, render); render.onclick = async () => { render.disabled = true; render.textContent = "Rendering…"; try { const response = await fetch("http://localhost:8000/study2/render", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ score: document.querySelector<HTMLInputElement>("#target-score")!.value, output: "reports/study-2/fixed-instrumental.wav", bpm: 120 }) }); if (!response.ok) throw new Error((await response.json()).detail); render.textContent = "Target rendered ✓"; } catch (error) { render.disabled = false; render.textContent = error instanceof Error ? error.message : "Unable to render target"; } }; }, 0);
    if (study === "study2" && step === "setup") window.setTimeout(() => { const paragraphs = stage.querySelectorAll("p"); if (paragraphs[0]) paragraphs[0].textContent = "Measure whether a source vocal’s content and melody remain stable when it is transferred onto a fixed, score-rendered target instrumental."; if (paragraphs[1]) paragraphs[1].textContent = "Assumptions: the source vocal and target score are readable PJS files. The score is rendered with the pinned additive-sine synthesizer before transfer; no generated accompaniment is used. Evaluation reports pitch difference, content-envelope similarity, duration error, and clipping."; const facts = stage.querySelectorAll(".facts span"); if (facts[1]) facts[1].textContent = "MusicXML-rendered WAV"; if (facts[4]) facts[4].textContent = "Fixed synth, tempo, gains"; }, 0);
    if (study === "study2" && step === "results") window.setTimeout(() => { const labels = document.querySelectorAll<HTMLElement>(".lineage b"); if (labels[0]) labels[0].textContent = "Transfer run"; if (labels[1]) labels[1].textContent = "Evaluation run"; }, 0);
    if (study === "study2" && step === "results") { const lineageWatcher = window.setInterval(() => { const status = document.querySelector<HTMLElement>("#evaluation-status"); const code = document.querySelector<HTMLElement>(".lineage div:nth-child(2) code"); if (status?.textContent?.includes("Evaluation completed") && code && evaluationRunId) { code.textContent = evaluationRunId; window.clearInterval(lineageWatcher); } }, 500); }
    if (study === "study2" && step === "results") { const decorateMetrics = window.setInterval(() => { const metrics = document.querySelector<HTMLElement>(".study2-metrics"); if (!metrics || document.querySelector(".study2-metric-note")) return; metrics.querySelectorAll("div").forEach((item) => { const label = item.querySelector("b")?.textContent || ""; const value = Number(item.querySelector("span")?.textContent); const good = label.includes("Pitch") ? value < 20 : label.includes("Voiced") || label.includes("Content") ? value >= (label.includes("Content") ? 0.7 : 0.8) : value < (label.includes("Duration") ? 0.1 : 1); item.classList.add(good ? "metric-good" : "metric-poor"); }); metrics.insertAdjacentHTML("afterend", `<aside class="metric-legend"><div><i class="legend-swatch legend-good"></i>Favorable range</div><div><i class="legend-swatch legend-poor"></i>Needs attention</div></aside><p class="note study2-metric-note">Pitch difference is mean absolute frame-level Hz error (lower is better: &lt;20 close, 20–50 moderate, &gt;50 large). Voiced-frame rate is the share of frames with pitch estimates (&gt;0.8 is strong). Content similarity is amplitude-envelope correlation (-1 to 1; &gt;0.7 strong, 0.4–0.7 moderate, &lt;0.4 weak). Duration error and output peak should be low; peaks above 1 indicate clipping risk.</p>`); window.clearInterval(decorateMetrics); }, 500); }
    if (step === "setup") stage.innerHTML = study === "study2" ? `<div class="card"><h2>Study 2 setup</h2><p>Measure whether a source vocal’s content and melody remain stable when it is transferred onto a separate target instrumental.</p><div class="facts"><div><b>Source</b><span>Mono vocal WAV</span></div><div><b>Target</b><span>Mono instrumental WAV</span></div><div><b>Output</b><span>Aligned vocal + target mix</span></div><div><b>Sample rate</b><span>16 kHz</span></div><div><b>Controls</b><span>Tempo, transpose, gains</span></div><div><b>Tracking</b><span>MLflow + parent lineage</span></div></div><p class="note">Assumptions: source and target are readable WAV files; both are resampled to 16 kHz mono. The control uses deterministic resampling and fixed gains. Evaluation reports pitch difference, content-envelope similarity, duration error, and clipping; it does not establish lyric intelligibility or human preference.</p><button id="next" class="primary">Continue <span>→</span></button></div>` : `<div class="card"><h2>Study setup</h2><p>${studies[study].setup} Results will be tracked with MLflow, Git revision, seed, and split fingerprint.</p><div class="facts"><div><b>Dataset</b><span>PJS v1.1</span></div><div><b>Split</b><span>80 / 10 / 10</span></div><div><b>Tracking</b><span>MLflow</span></div></div><button id="next" class="primary">Continue <span>→</span></button></div>`;
    if (step === "training") stage.innerHTML = study === "study1" ? `<div class="card"><h2>Train Study 1</h2><p>Start the score-conditioned baseline. The MLflow run ID will carry forward to evaluation.</p><button id="run" class="primary">Start training</button><pre id="status" class="output" hidden></pre></div>` : `<div class="card"><h2>Run Study 2 transfer</h2><p>Create a reproducible mix by aligning the source vocal to the target instrumental. Choose the two WAV files used for this comparison.</p><label>Source vocal<input id="source" value="data/raw/pjs/PJS_corpus_ver1.1/pjs099/pjs099_song.wav"></label><label>Target instrumental<input id="target" value="data/raw/pjs/PJS_corpus_ver1.1/pjs052/pjs052_song.wav"></label><button id="run" class="primary">Start transfer</button><pre id="status" class="output" hidden></pre></div>`;
    if (step === "results") stage.innerHTML = study === "study2" ? `<div class="card"><h2>Study 2 results</h2><p>Evaluate transfer against the source vocal. The report measures pitch preservation, content-envelope similarity, timing, and clipping.</p><div class="lineage"><div><b>Transfer</b><code>${runId || "pending"}</code></div><div><b>Evaluation</b><code>${evaluationRunId || "not run"}</code></div></div><button id="evaluate" class="primary">Run evaluation</button><pre id="evaluation-status" class="output" hidden></pre></div>` : `<div class="card"><h2>Results</h2><p>Run evaluation and review objective diagnostics and engineering audio artifacts. These results do not establish human preference or unseen-singer generalization.</p><div class="lineage"><div><b>Training</b><code>${runId || "pending"}</code></div><div><b>Evaluation</b><code>${evaluationRunId || "created after evaluation"}</code></div><div><b>Comparison</b><code>${comparisonRunId || "created after comparison"}</code></div></div><p class="note">Evaluation and comparison are separate MLflow runs. Their lineage must point back to the Training run; the IDs above make that relationship explicit.</p><button id="evaluate" class="primary">Run evaluation</button><pre id="evaluation-status" class="output" hidden></pre><div id="audio-results" class="audio-results"></div></div>`;
    if (step === "training") { const next = document.createElement("button"); next.className = "primary continue-training"; next.textContent = "Continue"; next.hidden = true; stage.append(next); const enable = (): void => { const status = document.querySelector<HTMLElement>("#status"); if (status && /Progress: (completed|completed-or-unknown)/.test(status.textContent || "")) next.hidden = false; else if (status && /Progress: failed/.test(status.textContent || "")) return; else window.setTimeout(enable, 1000); }; next.onclick = () => { step = "results"; draw(); }; window.setTimeout(enable, 1000); }
    document.querySelector<HTMLButtonElement>("#next")?.addEventListener("click", () => { step = "training"; draw(); });
    document.querySelector<HTMLButtonElement>("#evaluate")?.addEventListener("click", async () => { const output = document.querySelector<HTMLElement>("#evaluation-status")!; output.hidden = false; if (study === "study2") { output.textContent = "Launching objective evaluation…"; try { const response = await fetch("http://localhost:8000/study2/evaluation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference: "data/raw/pjs/PJS_corpus_ver1.1/pjs099/pjs099_song.wav", transferred: "reports/study-2/transfer.wav", output: "reports/study-2/evaluation.json", parent_run_id: runId }) }); if (!response.ok) throw new Error((await response.json()).detail); const job = await response.json() as { job_id: string }; const poll = async (): Promise<void> => { const status = await (await fetch(`http://localhost:8000/training/${job.job_id}`)).json() as { status: string; mlflow_run_id?: string; error?: string }; evaluationRunId = status.mlflow_run_id ?? evaluationRunId; output.textContent = `Evaluation ${status.status}\nMLflow run: ${evaluationRunId || "pending"}${status.error ? `\nError: ${status.error}` : ""}`; if (!["completed", "completed-or-unknown", "failed"].includes(status.status)) window.setTimeout(poll, 2000); }; poll(); } catch (error) { output.textContent = error instanceof Error ? error.message : "Unable to launch evaluation."; } return; } const audioResults = document.querySelector<HTMLElement>("#audio-results")!; output.textContent = `Loading comparison report for ${runId || "latest"}…`; try { const pointer = await (await fetch("/reports/latest.json")).json() as { run_id: string }; comparisonRunId = pointer.run_id; const manifest = await (await fetch(`/reports/${pointer.run_id}/manifest.json`)).json() as { examples: Array<{ id: string; reference: string; baseline: string; aligned: string }> }; const example = manifest.examples[0]; if (!example) throw new Error("No audio examples are available."); audioResults.innerHTML = `<h3>Playable audio · ${example.id}</h3>${([['Reference', example.reference], ['Baseline', example.baseline], ['Aligned', example.aligned]] as const).map(([label, path]) => `<label class="audio-item">${label}<audio controls preload="metadata" src="/reports/${pointer.run_id}/${path}"></audio></label>`).join("")}`; output.textContent = "Results loaded for this training run."; } catch (error) { output.textContent = error instanceof Error ? error.message : "Unable to load evaluation artifacts."; } });
    if (study === "study2" && step === "results") { let metricsLoaded = false; const metricsWatcher = window.setInterval(async () => { const status = document.querySelector<HTMLElement>("#evaluation-status"); if (!status || metricsLoaded || !status.textContent?.includes("Evaluation completed")) return; try { const report = await (await fetch("/reports/study-2/evaluation.json")).json() as { metrics: Record<string, number> }; const names: Record<string, string> = { pitch_difference_hz_mean: "Pitch difference (Hz)", pitch_voiced_frame_rate: "Voiced-frame rate", content_envelope_correlation: "Content similarity", duration_error_seconds: "Duration error (s)", output_peak: "Output peak" }; status.insertAdjacentHTML("afterend", `<div class="facts study2-metrics">${Object.entries(report.metrics).map(([name, value]) => `<div><b>${names[name] || name}</b><span>${value.toFixed(3)}</span></div>`).join("")}</div>`); metricsLoaded = true; window.clearInterval(metricsWatcher); } catch { /* report may not be visible until the mounted volume refreshes */ } }, 1000); }
    document.querySelector<HTMLButtonElement>("#run")?.addEventListener("click", () => launch(study));
  };
  const launch = (id: Study): void => { const out = document.querySelector<HTMLElement>("#status")!; out.hidden = false; out.textContent = "Launching Docker job…"; const body = id === "study1" ? { experiment: "conditioned", parameters: {} } : { experiment: "study2", source: (document.querySelector<HTMLInputElement>("#source")!).value, target: (document.querySelector<HTMLInputElement>("#target")!).value, output: "reports/study-2/transfer.wav" }; fetch("http://localhost:8000/training", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }).then(async (response) => { if (!response.ok) throw new Error((await response.json()).detail); const result = await response.json() as { job_id: string }; out.textContent = `Job ${result.job_id}\nProgress: queued`; const poll = async (): Promise<void> => { const status = await (await fetch(`http://localhost:8000/training/${result.job_id}`)).json() as { status: string; mlflow_run_id?: string; error?: string }; runId = status.mlflow_run_id ?? runId; out.textContent = `Job ${result.job_id}\nProgress: ${status.status}\nMLflow run: ${runId || "pending"}${status.error ? `\nError: ${status.error}` : ""}`; if (!["completed", "completed-or-unknown", "failed"].includes(status.status)) window.setTimeout(poll, 2000); }; window.setTimeout(poll, 1000); }).catch((error: unknown) => { out.textContent = `Unable to launch: ${error instanceof Error ? error.message : "API unavailable"}`; }); };
  draw();
}
landing();
